### PR TITLE
[WIP] Add TAC-LS supplies to crewed parts

### PR DESCRIPTION
**Pull request by LambdaSix**
Add life support supplies to crewed parts, that don't get covered by the default CommandModule handling, and add fuel cells to parts where it makes sense, like the Lander, Station Core, Science Labs

### CODE REVIEW

**Comment by LambdaSix** [comment]
For the sake of consistency, I'll rework the values to roughly match up with the USI LS patch, whichever is accepted.

**Comment by zorg2044** [comment]
Hi! Beale meant to merge my patch but accidentally did the other one, he said he's going to correct that shortly. Since you're interested in matching them up somewhat, I can in a little bit post my notes re durations and life support mass in case you find it helpful in the meantime.

**Comment by zorg2044** [comment]
Ok so here are my notes I made before making the patch with the supply masses and mission endurance. It should save you some time from having to parse the files :) I'm not very familiar with TAC-LS so trying to follow these USI values for TAC may or may not make sense...

Eridani_Crew_2(E-27KB Crew Module)
1.5 tons of supplies
46 days for 3 crew or or 69 for 2

I only added habitation (which I don't think is a factor in TAC-LS) to the E-27KA as its used in conjunction with E-27KB in Almaz, Salyut, Mir Core

Actual crew capacity is more but supplies were allocated for smaller crews of 2 or 3

Hamal_Habitation_1(H-FS1 Forward Section for Progress resupply craft)
1.5 tons of supplies

Tantares_Habitation_1 (T-OM1B Orbital Module for Soyuz)
0.375 tons of supplies 
11 days for crew of 3

Tantares_Orbital_1 (T-OM1 Orbital Module for Soyuz)
0.23 tons of supplies
7 days for crew of 3

Tantares_Habitation_2 and Tantares_Orbital_2 (T-SZ1B Habitation Section and T-SZ1 Habitation Section for Soyuz A)
0.75 tons of supplies
23 days of supplies for crew of 3

Tantares_Libra_Crew_1 (LK-15 lander)
0.075 tons of supplies
7 days for 1 crew 

Alniyat Crew 2_2 (For ISS Zarya and TKS supply craft)
3 tons of supplies
138 days for 2 or 92 days for 3 crew 

Alniyat Crew 2_1 (For MIR Kristall, Kvant 2, Spektre, Priroda)
1.5 tons of supplies
46 days for 3 crew or or 69 for 2

No other parts get supplies, only habitation.

Finally both Acamar Lab modules get 80% recycling. 
With an Acamar lab module, 3 tons of supplies will support 3 kerbals for 462 days.

Anyways hope these notes help you with your own patch!

**Comment by LambdaSix** [comment]
Thanks, this will help a lot, once I work out how to convert between the systems :)
Just haven't had any spare time to work on this for a while.

**Pull request closed without merging**
